const suraContents = {
    1: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ ۝ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ ۝ مَٰلِكِ يَوْمِ ٱلدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ۝ صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّالِّينَ<br>آمِينَ ۝ هَذِهِ السُّورَةُ هِيَ أُمُّ الْكِتَابِ وَتُسَمَّى الْفَاتِحَةُ لِأَنَّهَا تَفْتَحُ الْقُرْآنَ الْكَرِيمَ، وَهِيَ سَبْعُ آيَاتٍ تُقْرَأُ فِي كُلِّ رَكْعَةٍ مِنَ الصَّلَاةِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>All praise is due to Allah, Lord of the worlds, the Most Gracious, the Most Merciful, Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us to the straight path, the path of those upon whom You have bestowed favor, not of those who have earned Your anger, nor of those who are astray.<br>Amen. This surah, known as Al-Fatihah, is the opening chapter of the Quran and is recited in every unit of the Muslim prayer, consisting of seven verses.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Louange à Allah, Seigneur des mondes, le Tout Miséricordieux, le Très Miséricordieux, Maître du Jour du Jugement. C’est Toi que nous adorons, et c’est de Toi que nous implorons l’aide. Guide-nous sur le droit chemin, le chemin de ceux que Tu as comblés de bienfaits, non pas celui des réprouvés, ni des égarés.<br>Amen. Cette sourate, appelée Al-Fatihah, est la première du Coran et est récitée dans chaque unité de la prière musulmane, composée de sept versets."
    },
    2: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الم ۝ ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ ۝ ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ ۝ وَٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلْءَاخِرَةِ هُمْ يُوقِنُونَ<br>أُو۟لَٰٓئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ ۝ هَذِهِ السُّورَةُ هِيَ أَطْوَلُ سُورَةٍ فِي الْقُرْآنِ وَتَحْتَوِي عَلَىٰ قِصَصٍ وَأَحْكَامٍ شَرْعِيَّةٍ تُعَلِّمُ الْمُسْلِمِينَ كَيْفَ يَعِيشُونَ حَيَاةً مُسْتَقِيمَةً.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim. This is the Book about which there is no doubt, a guidance for those conscious of Allah, who believe in the unseen, establish prayer, and spend out of what We have provided for them, and who believe in what has been revealed to you and what was revealed before you, and of the Hereafter they are certain.<br>Those are upon guidance from their Lord, and those are the successful. This surah, Al-Baqarah, is the longest in the Quran and contains stories and legal rulings, teaching Muslims how to live a righteous life.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim. Ceci est le Livre au sujet duquel il n'y a aucun doute, un guide pour ceux qui craignent Allah, qui croient en l'invisible, accomplissent la prière et dépensent de ce que Nous leur avons attribué, et qui croient en ce qui t'a été révélé et en ce qui a été révélé avant toi, et qui sont certains de l'au-delà.<br>Ceux-là sont sur une guidance de leur Seigneur, et ce sont eux qui réussissent. Cette sourate, Al-Baqarah, est la plus longue du Coran et contient des récits et des lois, enseignant aux musulmans comment mener une vie droite."
    },
    3: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الم ۝ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۝ نَزَّلَ عَلَيْكَ ٱلْكِتَٰبَ بِٱلْحَقِّ مُصَدِّقًا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ ٱلتَّوْرَىٰةَ وَٱلْإِنجِيلَ ۝ مِن قَبْلُ هُدًى لِّلنَّاسِ وَأَنزَلَ ٱلْفُرْقَانَ ۝ إِنَّ ٱلَّذِينَ كَفَرُوا۟ بِآيَٰتِ ٱللَّهِ لَهُمْ عَذَابٌ شَدِيدٌ<br>وَٱللَّهُ عَزِيزٌ ذُو ٱنتِقَامٍ ۝ هَذِهِ السُّورَةُ تُسَمَّى آلَ عِمْرَانَ وَتَتَحَدَّثُ عَنْ قِصَصِ الْأَنْبِيَاءِ وَأَهْلِ الْكِتَابِ وَتُؤَكِّدُ عَلَىٰ أَهَمِّيَّةِ الإِيمَانِ بِٱللَّهِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim. Allah, there is no deity except Him, the Ever-Living, the Sustainer of existence. He has sent down upon you the Book in truth, confirming what was before it, and He revealed the Torah and the Gospel previously as guidance for the people, and He revealed the Criterion. Indeed, those who disbelieve in the signs of Allah will have a severe punishment.<br>And Allah is Exalted in Might, the Owner of Retribution. This surah, named Aal-E-Imran, speaks about the stories of the prophets and the People of the Book, emphasizing the importance of faith in Allah.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim. Allah, il n'y a de divinité sauf Lui, le Vivant, le Subsistant. Il a fait descendre sur toi le Livre en vérité, confirmant ce qui était avant lui, et Il a révélé la Torah et l'Évangile auparavant comme guidance pour les gens, et Il a révélé le Discernement. Certes, ceux qui mécroient aux signes d'Allah auront un châtiment sévère.<br>Et Allah est Tout-Puissant, Détenteur de la rétribution. Cette sourate, nommée Aal-E-Imran, parle des histoires des prophètes et des Gens du Livre, mettant en avant l'importance de la foi en Allah."
    },
    4: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَٰٓأَيُّهَا ٱلنَّاسُ ٱتَّقُوا۟ رَبَّكُمُ ٱلَّذِى خَلَقَكُم مِّن نَّفْسٍ وَٰحِدَةٍ وَخَلَقَ مِنْهَا زَوْجَهَا وَبَثَّ مِنْهُمَا رِجَالًا كَثِيرًا وَنِسَآءً ۝ وَٱتَّقُوا۟ ٱللَّهَ ٱلَّذِى تَسَآءَلُونَ بِهِۦ وَٱلْأَرْحَامَ ۝ إِنَّ ٱللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا<br>وَءَاتُوا۟ ٱلْيَتَٰمَىٰٓ أَمْوَٰلَهُمْ ۖ وَلَا تَتَبَدَّلُوا۟ ٱلْخَبِيثَ بِٱلطَّيِّبِ ۖ وَلَا تَأْكُلُوٓا۟ أَمْوَٰلَهُمْ إِلَىٰٓ أَمْوَٰلِكُمْ ۚ إِنَّهُۥ كَانَ حُوبًا كَبِيرًا ۝ هَذِهِ السُّورَةُ تُعْلِمُ الْمُسْلِمِينَ حُقُوقَ الْمَرْأَةِ وَالْيَتَامَىٰ وَتُؤَكِّدُ عَلَىٰ الْعَدْلِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>O mankind, fear your Lord, who created you from one soul and created from it its mate and dispersed from both of them many men and women. And fear Allah, through whom you ask one another, and the wombs. Indeed, Allah is ever, over you, an Observer.<br>And give to the orphans their properties and do not substitute the defective for the good. And do not consume their properties into your own. Indeed, that is a great sin. This surah teaches Muslims the rights of women and orphans and emphasizes justice.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ô hommes, craignez votre Seigneur qui vous a créés d'une seule âme et a créé d'elle son épouse, et a fait naître d'eux beaucoup d'hommes et de femmes. Craignez Allah au nom duquel vous vous implorez les uns les autres, ainsi que les liens de parenté. En vérité, Allah vous observe constamment.<br>Et donnez aux orphelins leurs biens, et ne substituez pas le mauvais au bon, et ne consommez pas leurs biens avec les vôtres, car cela est un grand péché. Cette sourate enseigne aux musulmans les droits des femmes et des orphelins et insiste sur la justice."
    },
    5: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ أَوْفُوا۟ بِٱلْعُقُودِ ۚ أُحِلَّتْ لَكُم بَهِيمَةُ ٱلْأَنْعَٰمِ إِلَّا مَا يُتْلَىٰ عَلَيْكُمْ غَيْرَ مُحِلِّى ٱلصَّيْدِ وَأَنتُمْ حُرُمٌ ۗ إِنَّ ٱللَّهَ يَحْكُمُ مَا يُرِيدُ ۝ يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ لَا تُحِلُّوا۟ شَعَٰٓئِرَ ٱللَّهِ وَلَا ٱلشَّهْرَ ٱلْحَرَامَ<br>وَلَا ٱلْهَدْىَ وَلَا ٱلْقَلَٰٓئِدَ وَلَآ ءَآمِّينَ ٱلْبَيْتَ ٱلْحَرَامَ ۖ يَبْتَغُونَ فَضْلًا مِّن رَّبِّهِمْ وَرِضْوَٰنًا ۗ هَذِهِ السُّورَةُ تَحْتَوِي عَلَىٰ أَحْكَامِ الْعُقُودِ وَالْحَلَالِ وَالْحَرَامِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>O you who have believed, fulfill your contracts. Lawful to you are the animals of grazing livestock except for that which is recited to you—hunting not being permitted while you are in the state of ihram. Indeed, Allah ordains what He intends. O you who have believed, do not violate the rites of Allah or the sacred month.<br>Nor the sacrificial animals, nor the garlands, nor those coming to the Sacred House seeking bounty from their Lord and His approval. This surah contains rulings on contracts, the lawful and the forbidden, guiding the believers in their daily lives.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ô vous qui avez cru, remplissez vos engagements. Les bêtes de bétail vous sont permises, sauf ce qui vous est récité, sans que la chasse soit permise lorsque vous êtes en état d'ihram. En vérité, Allah décide ce qu’Il veut. Ô vous qui avez cru, ne profanez pas les rites d’Allah ni le mois sacré.<br>Ni les offrandes, ni les guirlandes, ni ceux qui se rendent à la Maison Sacrée en quête de la grâce de leur Seigneur et de Sa satisfaction. Cette sourate contient des règles sur les contrats, le licite et l’illicite, guidant les croyants dans leur vie quotidienne."
    },
    6: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>ٱلْحَمْدُ لِلَّهِ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ وَجَعَلَ ٱلظُّلُمَٰتِ وَٱلنُّورَ ۖ ثُمَّ ٱلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ يَعْدِلُونَ ۝ هُوَ ٱلَّذِى خَلَقَكُم مِّن طِينٍ ثُمَّ قَضَىٰٓ أَجَلًا ۖ وَأَجَلٌ مُّسَمًّى عِندَهُۥ ۖ ثُمَّ أَنتُمْ تَمْتَرُونَ ۝ وَهُوَ ٱللَّهُ فِى ٱلسَّمَٰوَٰتِ وَفِى ٱلْأَرْضِ<br>يَعْلَمُ سِرَّكُمْ وَجَهْرَكُمْ وَيَعْلَمُ مَا تَكْسِبُونَ ۝ هَذِهِ السُّورَةُ تُؤَكِّدُ عَلَىٰ تَوْحِيدِ ٱللَّهِ وَتَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ إِبْرَاهِيمَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Praise be to Allah, who created the heavens and the earth and made the darkness and the light. Then those who disbelieve equate others with their Lord. It is He who created you from clay and then decreed a term and a specified time known to Him; yet you are in doubt. And He is Allah in the heavens and on the earth.<br>He knows your secret and what you make public, and He knows that which you earn. This surah emphasizes the oneness of Allah and narrates stories of prophets like Abraham, teaching lessons of faith and obedience.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Louange à Allah, qui a créé les cieux et la terre et a fait les ténèbres et la lumière. Puis ceux qui mécroient attribuent des égaux à leur Seigneur. C’est Lui qui vous a créés d’argile, puis a fixé un terme, et un terme déterminé est auprès de Lui ; et pourtant vous doutez. Il est Allah dans les cieux et sur la terre.<br>Il connaît votre secret et ce que vous divulguez, et Il sait ce que vous acquérez. Cette sourate met l’accent sur l’unicité d’Allah et raconte les histoires de prophètes comme Abraham, enseignant des leçons de foi et d’obéissance."
    },
    7: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>المص ۝ كِتَٰبٌ أُنزِلَ إِلَيْكَ فَلَا يَكُن فِى صَدْرِكَ حَرَجٌ مِّنْهُ لِتُنذِرَ بِهِۦ وَذِكْرَىٰ لِلْمُؤْمِنِينَ ۝ ٱتَّبِعُوا۟ مَآ أُنزِلَ إِلَيْكُم مِّن رَّبِّكُمْ وَلَا تَتَّبِعُوا۟ مِن دُونِهِۦٓ أَوْلِيَآءَ ۗ قَلِيلًا مَّا تَذَكَّرُونَ ۝ وَكَم مِّن قَرْيَةٍ أَهْلَكْنَٰهَا فَجَآءَهَا بَأْسُنَا بَيَٰتًا أَوْ هُمْ قَآئِلُونَ<br>فَمَا كَانَ دَعْوَىٰهُمْ إِذْ جَآءَهُم بَأْسُنَآ إِلَّآ أَن قَالُوٓا۟ إِنَّا كُنَّا ظَٰلِمِينَ ۝ هَذِهِ السُّورَةُ تَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ نُوحٍ وَمُوسَىٰ وَتُحَذِّرُ مِنَ الْعَذَابِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim Sad. A Book revealed to you—so let there be no discomfort in your heart from it—that you may warn thereby and as a reminder to the believers. Follow what has been revealed to you from your Lord and do not follow other than Him as allies. Little do you remember. And how many a city We destroyed, and Our punishment came to them at night or while they were sleeping at noon.<br>Then their plea when Our punishment came to them was only that they said, 'Indeed, we were wrongdoers.' This surah narrates the stories of prophets like Noah and Moses, warning against the punishment for disbelief.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim Sad. Un Livre qui t’a été révélé—qu’il n’y ait donc pas de gêne dans ton cœur à cause de lui—afin que tu avertisses par lui et qu’il soit un rappel pour les croyants. Suivez ce qui vous a été révélé de votre Seigneur et ne suivez pas d’autres alliés en dehors de Lui. Peu vous vous souvenez. Combien de cités avons-Nous détruites, et Notre châtiment leur est venu la nuit ou pendant qu’ils faisaient la sieste à midi.<br>Leur seule plainte, lorsque Notre châtiment les atteignit, fut de dire : 'En vérité, nous étions injustes.' Cette sourate raconte les histoires de prophètes comme Noé et Moïse, mettant en garde contre le châtiment pour l’incroyance."
    },
    8: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَسْـَٔلُونَكَ عَنِ ٱلْأَنفَالِ ۖ قُلِ ٱلْأَنفَالُ لِلَّهِ وَٱلرَّسُولِ ۖ فَٱتَّقُوا۟ ٱللَّهَ وَأَصْلِحُوا۟ ذَاتَ بَيْنِكُمْ ۖ وَأَطِيعُوا۟ ٱللَّهَ وَرَسُولَهُۥٓ إِن كُنتُم مُّؤْمِنِينَ ۝ إِنَّمَا ٱلْمُؤْمِنُونَ ٱلَّذِينَ إِذَا ذُكِرَ ٱللَّهُ وَجِلَتْ قُلُوبُهُمْ وَإِذَا تُلِيَتْ عَلَيْهِمْ ءَايَٰتُهُۥ زَادَتْهُمْ إِيمَٰنًا<br>وَعَلَىٰ رَبِّهِمْ يَتَوَكَّلُونَ ۝ هَذِهِ السُّورَةُ تَتَحَدَّثُ عَنْ غَنَائِمِ الْحَرْبِ وَمَعْرَكَةِ بَدْرٍ وَتُعَلِّمُ الْمُؤْمِنِينَ الصَّبْرَ وَالطَّاعَةَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>They ask you about the spoils of war. Say, 'The spoils belong to Allah and the Messenger, so fear Allah and set right the matters between you, and obey Allah and His Messenger if you are believers.' The true believers are those whose hearts tremble when Allah is mentioned, and when His verses are recited to them, it increases their faith.<br>And they rely upon their Lord. This surah discusses the spoils of war and the Battle of Badr, teaching the believers patience and obedience to Allah and His Messenger.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ils te questionnent au sujet des butins. Dis : 'Les butins appartiennent à Allah et au Messager, alors craignez Allah et réglez vos différends, et obéissez à Allah et à Son Messager si vous êtes croyants.' Les vrais croyants sont ceux dont les cœurs frémissent quand Allah est mentionné, et lorsque Ses versets leur sont récités, cela augmente leur foi.<br>Et ils s’en remettent à leur Seigneur. Cette sourate parle des butins de guerre et de la bataille de Badr, enseignant aux croyants la patience et l’obéissance à Allah et à Son Messager."
    },
    9: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>بَرَاءَةٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلَّذِينَ عَٰهَدتُّم مِّنَ ٱلْمُشْرِكِينَ ۝ فَسِيحُوا۟ فِى ٱلْأَرْضِ أَرْبَعَةَ أَشْهُرٍ وَٱعْلَمُوٓا۟ أَنَّكُمْ غَيْرُ مُعْجِزِى ٱللَّهِ ۖ وَأَنَّ ٱللَّهَ مُخْزِى ٱلْكَٰفِرِينَ ۝ وَأَذَٰنٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلنَّاسِ يَوْمَ ٱلْحَجِّ ٱلْأَكْبَرِ<br>أَنَّ ٱللَّهَ بَرِىٓءٌ مِّنَ ٱلْمُشْرِكِينَ ۙ وَرَسُولُهُۥ ۚ هَذِهِ السُّورَةُ تُعْلِنُ انْتِهَاءَ الْعَهْدِ مَعَ الْمُشْرِكِينَ وَتُحَدِّدُ أَحْكَامَ الْجِهَادِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>A declaration of disassociation from Allah and His Messenger to those with whom you had made a treaty among the polytheists. So travel freely in the land for four months but know that you cannot escape Allah and that Allah will disgrace the disbelievers. And an announcement from Allah and His Messenger to the people on the day of the greater pilgrimage.<br>That Allah is free from the polytheists, and so is His Messenger. This surah declares the end of treaties with the polytheists and outlines the rules of jihad, emphasizing the importance of upholding faith.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Une déclaration de rupture de la part d’Allah et de Son Messager envers ceux des polythéistes avec lesquels vous aviez conclu un pacte. Parcourez librement la terre pendant quatre mois, mais sachez que vous ne saurez échapper à Allah et qu’Allah couvrira d’opprobre les mécréants. Et un appel d’Allah et de Son Messager aux gens le jour du grand pèlerinage.<br>Qu’Allah est dégagé des polythéistes, ainsi que Son Messager. Cette sourate annonce la fin des pactes avec les polythéistes et établit les règles du jihad, soulignant l’importance de maintenir la foi."
    },
    10: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ٱلْحَكِيمِ ۝ أَكَانَ لِلنَّاسِ عَجَبًا أَنْ أَوْحَيْنَآ إِلَىٰ رَجُلٍ مِّنْهُمْ أَنْ أَنذِرِ ٱلنَّاسَ وَبَشِّرِ ٱلَّذِينَ ءَامَنُوٓا۟ أَنَّ لَهُمْ قَدَمَ صِدْقٍ عِندَ رَبِّهِمْ ۗ قَالَ ٱلْكَٰفِرُونَ إِنَّ هَٰذَا لَسَٰحِرٌ مُّبِينٌ ۝ إِنَّ رَبَّكُمُ ٱللَّهُ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ فِى سِتَّةِ أَيَّامٍ<br>ثُمَّ ٱسْتَوَىٰ عَلَى ٱلْعَرْشِ ۖ يُدَبِّرُ ٱلْأَمْرَ ۖ مَا مِن شَفِيعٍ إِلَّا مِنۢ بَعْدِ إِذْنِهِۦ ۚ ذَٰلِكُمُ ٱللَّهُ رَبُّكُمْ فَٱعْبُدُوهُ ۚ هَذِهِ السُّورَةُ تُسَمَّى يُونُسْ وَتُرَكِّزُ عَلَىٰ دَعْوَةِ الْأَنْبِيَاءِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the wise Book. Was it a wonder to the people that We revealed to a man from among them that he should warn the people and give good tidings to those who believe that they will have a noble reward with their Lord? The disbelievers say, 'Indeed, this is an obvious magician.' Indeed, your Lord is Allah, who created the heavens and the earth in six days.<br>Then He established Himself on the Throne, arranging the matter; there is no intercessor except after His permission. That is Allah, your Lord, so worship Him. This surah, named Yunus, focuses on the mission of the prophets and their call to worship Allah alone.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre sage. Est-ce une chose étonnante pour les gens que Nous ayons révélé à un homme d’entre eux de mettre en garde les gens et d’annoncer la bonne nouvelle à ceux qui croient qu’ils auront une belle récompense auprès de leur Seigneur ? Les mécréants disent : 'Ceci est un magicien manifeste.' En vérité, votre Seigneur est Allah, qui a créé les cieux et la terre en six jours.<br>Puis Il S’est établi sur le Trône, gérant l’ordre ; il n’y a d’intercesseur qu’avec Sa permission. Tel est Allah, votre Seigneur, alors adorez-Le. Cette sourate, nommée Yunus, met l’accent sur la mission des prophètes et leur appel à adorer Allah seul."
    },
    11: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ كِتَٰبٌ أُحْكِمَتْ ءَايَٰتُهُۥ ثُمَّ فُصِّلَتْ مِن لَّدُنْ حَكِيمٍ خَبِيرٍ ۝ أَلَّا تَعْبُدُوٓا۟ إِلَّا ٱللَّهَ ۚ إِنَّنِى لَكُم مِّنْهُ نَذِيرٌ وَبَشِيرٌ ۝ وَأَنِ ٱسْتَغْفِرُوا۟ رَبَّكُمْ ثُمَّ تُوبُوٓا۟ إِلَيْهِ يُمَتِّعْكُم مَّتَٰعًا حَسَنًا إِلَىٰٓ أَجَلٍ مُّسَمًّى وَيُؤْتِ كُلَّ ذِى فَضْلٍ فَضْلَهُۥ ۖ وَإِن تَوَلَّوْا۟ فَإِنِّىٓ أَخَافُ عَلَيْكُمْ عَذَابَ يَوْمٍ كَبِيرٍ<br>إِلَى ٱللَّهِ مَرْجِعُكُمْ ۖ وَهُوَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ ۝ هَذِهِ السُّورَةُ تُسَمَّى هُودٍ وَتَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ نُوحٍ وَهُودٍ وَصَالِحٍ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. A Book whose verses have been detailed, then distinguished from One who is Wise and Acquainted. [Saying], 'Worship none but Allah. Indeed, I am to you from Him a warner and a bringer of good tidings.' And [saying], 'Seek forgiveness of your Lord and repent to Him, and He will let you enjoy a good provision for a specified term and give every doer of favor his favor. But if you turn away, then I fear for you the punishment of a great Day.'<br>To Allah is your return, and He is over all things competent. This surah, named Hud, narrates the stories of prophets like Noah, Hud, and Salih, highlighting their warnings and the consequences of disbelief.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Un Livre dont les versets ont été détaillés, puis distingués, de la part d’un Sage, parfaitement Informé. [Disant] : 'N’adorez qu’Allah. En vérité, je suis pour vous, de Sa part, un avertisseur et un annonciateur de bonne nouvelle.' Et [disant] : 'Demandez pardon à votre Seigneur et repentez-vous à Lui, Il vous fera jouir d’une belle provision jusqu’à un terme fixé et accordera à tout homme de mérite sa récompense. Mais si vous vous détournez, je crains pour vous le châtiment d’un jour terrible.'<br>C’est vers Allah que vous retournerez, et Il est capable de toute chose. Cette sourate, nommée Hud, raconte les histoires des prophètes comme Noé, Hud et Salih, mettant en lumière leurs avertissements et les conséquences de l’incroyance."
    },
    12: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ٱلْمُبِينِ ۝ إِنَّآ أَنزَلْنَٰهُ قُرْءَانًا عَرَبِيًّا لَّعَلَّكُمْ تَعْقِلُونَ ۝ نَحْنُ نَقُصُّ عَلَيْكَ أَحْسَنَ ٱلْقَصَصِ بِمَآ أَوْحَيْنَآ إِلَيْكَ هَٰذَا ٱلْقُرْءَانَ وَإِن كُنتَ مِن قَبْلِهِۦ لَمِنَ ٱلْغَٰفِلِينَ ۝ إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَٰٓأَبَتِ إِنِّى رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًا وَٱلشَّمْسَ وَٱلْقَمَرَ رَأَيْتُهُمْ لِى سَٰجِدِينَ<br>قَالَ يَٰبُنَىَّ لَا تَقْصُصْ رُءْيَاكَ عَلَىٰٓ إِخْوَتِكَ فَيَكِيدُوا۟ لَكَ كَيْدًا ۖ إِنَّ ٱلشَّيْطَٰنَ لِلْإِنسَٰنِ عَدُوٌّ مُّبِينٌ ۝ هَذِهِ السُّورَةُ تَحْكِي قِصَّةَ يُوسُفَ عَلَيْهِ السَّلَامُ وَتُعَلِّمُ الصَّبْرَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the clear Book. Indeed, We have sent it down as an Arabic Quran that you might understand. We relate to you the best of stories in what We have revealed to you of this Quran, although you were, before it, among the unaware. When Joseph said to his father, 'O my father, indeed I have seen eleven stars and the sun and the moon; I saw them prostrating to me.'<br>He said, 'O my son, do not relate your vision to your brothers or they will contrive against you a plan. Indeed, Satan is to man a clear enemy.' This surah tells the story of Prophet Joseph (Yusuf) and teaches the virtue of patience in the face of trials.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre clair. En vérité, Nous l’avons fait descendre en un Coran arabe afin que vous raisonniez. Nous te racontons la plus belle des histoires par ce que Nous t’avons révélé de ce Coran, bien que tu fusses auparavant parmi les ignorants. Lorsque Joseph dit à son père : 'Ô mon père, j’ai vu onze étoiles, le soleil et la lune ; je les ai vus se prosterner devant moi.'<br>Il dit : 'Ô mon fils, ne raconte pas ta vision à tes frères, de peur qu’ils ne trament un complot contre toi. En vérité, Satan est pour l’homme un ennemi déclaré.' Cette sourate raconte l’histoire du prophète Joseph (Yusuf) et enseigne la vertu de la patience face aux épreuves."
    },
    13: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>المر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ۗ وَٱلَّذِىٓ أُنزِلَ إِلَيْكَ مِن رَّبِّكَ ٱلْحَقُّ وَلَٰكِنَّ أَكْثَرَ ٱلنَّاسِ لَا يُؤْمِنُونَ ۝ ٱللَّهُ ٱلَّذِى رَفَعَ ٱلسَّمَٰوَٰتِ بِغَيْرِ عَمَدٍ تَرَوْنَهَا ۖ ثُمَّ ٱسْتَوَىٰ عَلَى ٱلْعَرْشِ ۖ وَسَخَّرَ ٱلشَّمْسَ وَٱلْقَمَرَ ۖ كُلٌّ يَجْرِى لِأَجَلٍ مُّسَمًّى ۚ يُدَبِّرُ ٱلْأَمْرَ يُفَصِّلُ ٱلْءَايَٰتِ لَعَلَّكُم بِلِقَآءِ رَبِّكُمْ تُوقِنُونَ<br>وَهُوَ ٱلَّذِى مَدَّ ٱلْأَرْضَ وَجَعَلَ فِيهَا رَوَٰسِىَ وَأَنْهَٰرًا ۖ هَذِهِ السُّورَةُ تُسَمَّى الرَّعْدِ وَتُرَكِّزُ عَلَىٰ عَظَمَةِ خَلْقِ ٱللَّهِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim Ra. These are the verses of the Book. And what has been revealed to you from your Lord is the truth, but most of the people do not believe. Allah is the One who raised the heavens without pillars that you can see; then He established Himself on the Throne and subjected the sun and the moon, each running its course for a specified term. He arranges the matter; He details the signs that you may be certain of the meeting with your Lord.<br>And it is He who spread the earth and placed therein firmly set mountains and rivers. This surah, named Ar-Ra'd (The Thunder), focuses on the greatness of Allah's creation and His signs in the universe.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim Ra. Ce sont les versets du Livre. Et ce qui t’a été révélé de ton Seigneur est la vérité, mais la plupart des gens ne croient pas. Allah est Celui qui a élevé les cieux sans piliers visibles ; puis Il S’est établi sur le Trône et a soumis le soleil et la lune, chacun courant jusqu’à un terme fixé. Il gère l’ordre et détaille les signes afin que vous soyez certains de la rencontre avec votre Seigneur.<br>Et c’est Lui qui a étendu la terre et y a placé des montagnes immobiles et des rivières. Cette sourate, nommée Ar-Ra'd (Le Tonnerre), met l’accent sur la grandeur de la création d’Allah et Ses signes dans l’univers."
    },
    14: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ كِتَٰبٌ أَنزَلْنَٰهُ إِلَيْكَ لِتُخْرِجَ ٱلنَّاسَ مِنَ ٱلظُّلُمَٰتِ إِلَى ٱلنُّورِ بِإِذْنِ رَبِّهِمْ إِلَىٰ صِرَٰطِ ٱلْعَزِيزِ ٱلْحَمِيدِ ۝ ٱللَّهِ ٱلَّذِى لَهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ وَوَيْلٌ لِّلْكَٰفِرِينَ مِنْ عَذَابٍ شَدِيدٍ ۝ ٱلَّذِينَ يَسْتَحِبُّونَ ٱلْحَيَوٰةَ ٱلدُّنْيَا عَلَى ٱلْءَاخِرَةِ وَيَصُدُّونَ عَن سَبِيلِ ٱللَّهِ وَيَبْغُونَهَا عِوَجًا ۚ أُو۟لَٰٓئِكَ فِى ضَلَٰلٍۢ بَعِيدٍ<br>وَمَآ أَرْسَلْنَا مِن رَّسُولٍ إِلَّا بِلِسَانِ قَوْمِهِۦ لِيُبَيِّنَ لَهُمْ ۖ هَذِهِ السُّورَةُ تُسَمَّى إِبْرَاهِيمَ وَتُرَكِّزُ عَلَىٰ دَعْوَةِ الْأَنْبِيَاءِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. A Book which We have revealed to you that you might bring mankind out of darknesses into the light by the permission of their Lord—to the path of the Exalted in Might, the Praiseworthy—Allah, to whom belongs whatever is in the heavens and whatever is on the earth. And woe to the disbelievers from a severe punishment—the ones who prefer the worldly life over the Hereafter and avert people from the way of Allah, seeking to make it crooked. Those are in far error.<br>And We did not send any messenger except in the language of his people to state clearly for them. This surah, named Ibrahim, focuses on the call of the prophets to guide people to the truth.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Un Livre que Nous t’avons révélé afin que tu fasses sortir les gens des ténèbres vers la lumière, par la permission de leur Seigneur, vers le chemin du Tout-Puissant, Digne de louange—Allah, à qui appartient tout ce qui est dans les cieux et sur la terre. Et malheur aux mécréants à cause d’un châtiment sévère—ceux qui préfèrent la vie d’ici-bas à l’au-delà, qui détournent les gens du chemin d’Allah et cherchent à le rendre tortueux. Ceux-là sont dans un égarement profond.<br>Et Nous n’avons envoyé de messager qu’avec la langue de son peuple afin qu’il leur explique clairement. Cette sourate, nommée Ibrahim, met l’accent sur l’appel des prophètes à guider les gens vers la vérité."
    },
    15: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ وَقُرْءَانٍ مُّبِينٍ ۝ رُّبَمَا يَوَدُّ ٱلَّذِينَ كَفَرُوٓا۟ لَوْ كَانُوا۟ مُسْلِمِينَ ۝ ذَرْهُمْ يَأْكُلُوا۟ وَيَتَمَتَّعُوا۟ وَيُلْهِهِمُ ٱلْأَمَلُ ۖ فَسَوْفَ يَعْلَمُونَ ۝ وَمَآ أَهْلَكْنَا مِن قَرْيَةٍ إِلَّا وَلَهَا كِتَٰبٌ مَّعْلُومٌ ۝ مَّا تَسْبِقُ مِنْ أُمَّةٍ أَجَلَهَا وَمَا يَسْتَـْٔخِرُونَ<br>وَقَالُوا۟ يَٰٓأَيُّهَا ٱلَّذِى نُزِّلَ عَلَيْهِ ٱلذِّكْرُ إِنَّكَ لَمَجْنُونٌ ۖ هَذِهِ السُّورَةُ تُسَمَّى الْحِجْرِ وَتُرَكِّزُ عَلَىٰ قِصَصِ الْأَقْوَامِ الْمُهْلَكَةِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the Book and a clear Quran. Perhaps those who disbelieve will wish that they had been Muslims. Let them eat and enjoy themselves and be diverted by false hope, for they will come to know. And We did not destroy any city but that it had a known decree. No nation can advance its term, nor can they delay it.<br>And they say, 'O you upon whom the message has been sent down, indeed you are mad.' This surah, named Al-Hijr, focuses on the stories of destroyed nations and serves as a warning to those who reject the truth.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre et d’un Coran clair. Peut-être que ceux qui mécroient souhaiteraient avoir été musulmans. Laisse-les manger, jouir et se laisser distraire par de faux espoirs, car bientôt ils sauront. Nous n’avons détruit aucune cité sans qu’elle ait eu un décret connu. Aucune nation ne peut devancer son terme ni le retarder.<br>Et ils disent : 'Ô toi sur qui le Rappel a été descendu, tu es certes un fou.' Cette sourate, nommée Al-Hijr, met l’accent sur les histoires des peuples détruits et sert d’avertissement à ceux qui rejettent la vérité."
    },
  16: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الم ۝ ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ ۝ ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ ۝ وَٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلْءَاخِرَةِ هُمْ يُوقِنُونَ<br>أُو۟لَٰٓئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ ۝ هَذِهِ السُّورَةُ هِيَ أَطْوَلُ سُورَةٍ فِي الْقُرْآنِ وَتَحْتَوِي عَلَىٰ قِصَصٍ وَأَحْكَامٍ شَرْعِيَّةٍ تُعَلِّمُ الْمُسْلِمِينَ كَيْفَ يَعِيشُونَ حَيَاةً مُسْتَقِيمَةً.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim. This is the Book about which there is no doubt, a guidance for those conscious of Allah, who believe in the unseen, establish prayer, and spend out of what We have provided for them, and who believe in what has been revealed to you and what was revealed before you, and of the Hereafter they are certain.<br>Those are upon guidance from their Lord, and those are the successful. This surah, Al-Baqarah, is the longest in the Quran and contains stories and legal rulings, teaching Muslims how to live a righteous life.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim. Ceci est le Livre au sujet duquel il n'y a aucun doute, un guide pour ceux qui craignent Allah, qui croient en l'invisible, accomplissent la prière et dépensent de ce que Nous leur avons attribué, et qui croient en ce qui t'a été révélé et en ce qui a été révélé avant toi, et qui sont certains de l'au-delà.<br>Ceux-là sont sur une guidance de leur Seigneur, et ce sont eux qui réussissent. Cette sourate, Al-Baqarah, est la plus longue du Coran et contient des récits et des lois, enseignant aux musulmans comment mener une vie droite."
    },
    17: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الم ۝ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۝ نَزَّلَ عَلَيْكَ ٱلْكِتَٰبَ بِٱلْحَقِّ مُصَدِّقًا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ ٱلتَّوْرَىٰةَ وَٱلْإِنجِيلَ ۝ مِن قَبْلُ هُدًى لِّلنَّاسِ وَأَنزَلَ ٱلْفُرْقَانَ ۝ إِنَّ ٱلَّذِينَ كَفَرُوا۟ بِآيَٰتِ ٱللَّهِ لَهُمْ عَذَابٌ شَدِيدٌ<br>وَٱللَّهُ عَزِيزٌ ذُو ٱنتِقَامٍ ۝ هَذِهِ السُّورَةُ تُسَمَّى آلَ عِمْرَانَ وَتَتَحَدَّثُ عَنْ قِصَصِ الْأَنْبِيَاءِ وَأَهْلِ الْكِتَابِ وَتُؤَكِّدُ عَلَىٰ أَهَمِّيَّةِ الإِيمَانِ بِٱللَّهِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim. Allah, there is no deity except Him, the Ever-Living, the Sustainer of existence. He has sent down upon you the Book in truth, confirming what was before it, and He revealed the Torah and the Gospel previously as guidance for the people, and He revealed the Criterion. Indeed, those who disbelieve in the signs of Allah will have a severe punishment.<br>And Allah is Exalted in Might, the Owner of Retribution. This surah, named Aal-E-Imran, speaks about the stories of the prophets and the People of the Book, emphasizing the importance of faith in Allah.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim. Allah, il n'y a de divinité sauf Lui, le Vivant, le Subsistant. Il a fait descendre sur toi le Livre en vérité, confirmant ce qui était avant lui, et Il a révélé la Torah et l'Évangile auparavant comme guidance pour les gens, et Il a révélé le Discernement. Certes, ceux qui mécroient aux signes d'Allah auront un châtiment sévère.<br>Et Allah est Tout-Puissant, Détenteur de la rétribution. Cette sourate, nommée Aal-E-Imran, parle des histoires des prophètes et des Gens du Livre, mettant en avant l'importance de la foi en Allah."
    },
    18: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَٰٓأَيُّهَا ٱلنَّاسُ ٱتَّقُوا۟ رَبَّكُمُ ٱلَّذِى خَلَقَكُم مِّن نَّفْسٍ وَٰحِدَةٍ وَخَلَقَ مِنْهَا زَوْجَهَا وَبَثَّ مِنْهُمَا رِجَالًا كَثِيرًا وَنِسَآءً ۝ وَٱتَّقُوا۟ ٱللَّهَ ٱلَّذِى تَسَآءَلُونَ بِهِۦ وَٱلْأَرْحَامَ ۝ إِنَّ ٱللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا<br>وَءَاتُوا۟ ٱلْيَتَٰمَىٰٓ أَمْوَٰلَهُمْ ۖ وَلَا تَتَبَدَّلُوا۟ ٱلْخَبِيثَ بِٱلطَّيِّبِ ۖ وَلَا تَأْكُلُوٓا۟ أَمْوَٰلَهُمْ إِلَىٰٓ أَمْوَٰلِكُمْ ۚ إِنَّهُۥ كَانَ حُوبًا كَبِيرًا ۝ هَذِهِ السُّورَةُ تُعْلِمُ الْمُسْلِمِينَ حُقُوقَ الْمَرْأَةِ وَالْيَتَامَىٰ وَتُؤَكِّدُ عَلَىٰ الْعَدْلِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>O mankind, fear your Lord, who created you from one soul and created from it its mate and dispersed from both of them many men and women. And fear Allah, through whom you ask one another, and the wombs. Indeed, Allah is ever, over you, an Observer.<br>And give to the orphans their properties and do not substitute the defective for the good. And do not consume their properties into your own. Indeed, that is a great sin. This surah teaches Muslims the rights of women and orphans and emphasizes justice.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ô hommes, craignez votre Seigneur qui vous a créés d'une seule âme et a créé d'elle son épouse, et a fait naître d'eux beaucoup d'hommes et de femmes. Craignez Allah au nom duquel vous vous implorez les uns les autres, ainsi que les liens de parenté. En vérité, Allah vous observe constamment.<br>Et donnez aux orphelins leurs biens, et ne substituez pas le mauvais au bon, et ne consommez pas leurs biens avec les vôtres, car cela est un grand péché. Cette sourate enseigne aux musulmans les droits des femmes et des orphelins et insiste sur la justice."
    },
    19: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ أَوْفُوا۟ بِٱلْعُقُودِ ۚ أُحِلَّتْ لَكُم بَهِيمَةُ ٱلْأَنْعَٰمِ إِلَّا مَا يُتْلَىٰ عَلَيْكُمْ غَيْرَ مُحِلِّى ٱلصَّيْدِ وَأَنتُمْ حُرُمٌ ۗ إِنَّ ٱللَّهَ يَحْكُمُ مَا يُرِيدُ ۝ يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ لَا تُحِلُّوا۟ شَعَٰٓئِرَ ٱللَّهِ وَلَا ٱلشَّهْرَ ٱلْحَرَامَ<br>وَلَا ٱلْهَدْىَ وَلَا ٱلْقَلَٰٓئِدَ وَلَآ ءَآمِّينَ ٱلْبَيْتَ ٱلْحَرَامَ ۖ يَبْتَغُونَ فَضْلًا مِّن رَّبِّهِمْ وَرِضْوَٰنًا ۗ هَذِهِ السُّورَةُ تَحْتَوِي عَلَىٰ أَحْكَامِ الْعُقُودِ وَالْحَلَالِ وَالْحَرَامِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>O you who have believed, fulfill your contracts. Lawful to you are the animals of grazing livestock except for that which is recited to you—hunting not being permitted while you are in the state of ihram. Indeed, Allah ordains what He intends. O you who have believed, do not violate the rites of Allah or the sacred month.<br>Nor the sacrificial animals, nor the garlands, nor those coming to the Sacred House seeking bounty from their Lord and His approval. This surah contains rulings on contracts, the lawful and the forbidden, guiding the believers in their daily lives.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ô vous qui avez cru, remplissez vos engagements. Les bêtes de bétail vous sont permises, sauf ce qui vous est récité, sans que la chasse soit permise lorsque vous êtes en état d'ihram. En vérité, Allah décide ce qu’Il veut. Ô vous qui avez cru, ne profanez pas les rites d’Allah ni le mois sacré.<br>Ni les offrandes, ni les guirlandes, ni ceux qui se rendent à la Maison Sacrée en quête de la grâce de leur Seigneur et de Sa satisfaction. Cette sourate contient des règles sur les contrats, le licite et l’illicite, guidant les croyants dans leur vie quotidienne."
    },
    20: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>ٱلْحَمْدُ لِلَّهِ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ وَجَعَلَ ٱلظُّلُمَٰتِ وَٱلنُّورَ ۖ ثُمَّ ٱلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ يَعْدِلُونَ ۝ هُوَ ٱلَّذِى خَلَقَكُم مِّن طِينٍ ثُمَّ قَضَىٰٓ أَجَلًا ۖ وَأَجَلٌ مُّسَمًّى عِندَهُۥ ۖ ثُمَّ أَنتُمْ تَمْتَرُونَ ۝ وَهُوَ ٱللَّهُ فِى ٱلسَّمَٰوَٰتِ وَفِى ٱلْأَرْضِ<br>يَعْلَمُ سِرَّكُمْ وَجَهْرَكُمْ وَيَعْلَمُ مَا تَكْسِبُونَ ۝ هَذِهِ السُّورَةُ تُؤَكِّدُ عَلَىٰ تَوْحِيدِ ٱللَّهِ وَتَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ إِبْرَاهِيمَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Praise be to Allah, who created the heavens and the earth and made the darkness and the light. Then those who disbelieve equate others with their Lord. It is He who created you from clay and then decreed a term and a specified time known to Him; yet you are in doubt. And He is Allah in the heavens and on the earth.<br>He knows your secret and what you make public, and He knows that which you earn. This surah emphasizes the oneness of Allah and narrates stories of prophets like Abraham, teaching lessons of faith and obedience.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Louange à Allah, qui a créé les cieux et la terre et a fait les ténèbres et la lumière. Puis ceux qui mécroient attribuent des égaux à leur Seigneur. C’est Lui qui vous a créés d’argile, puis a fixé un terme, et un terme déterminé est auprès de Lui ; et pourtant vous doutez. Il est Allah dans les cieux et sur la terre.<br>Il connaît votre secret et ce que vous divulguez, et Il sait ce que vous acquérez. Cette sourate met l’accent sur l’unicité d’Allah et raconte les histoires de prophètes comme Abraham, enseignant des leçons de foi et d’obéissance."
    },
    21: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>المص ۝ كِتَٰبٌ أُنزِلَ إِلَيْكَ فَلَا يَكُن فِى صَدْرِكَ حَرَجٌ مِّنْهُ لِتُنذِرَ بِهِۦ وَذِكْرَىٰ لِلْمُؤْمِنِينَ ۝ ٱتَّبِعُوا۟ مَآ أُنزِلَ إِلَيْكُم مِّن رَّبِّكُمْ وَلَا تَتَّبِعُوا۟ مِن دُونِهِۦٓ أَوْلِيَآءَ ۗ قَلِيلًا مَّا تَذَكَّرُونَ ۝ وَكَم مِّن قَرْيَةٍ أَهْلَكْنَٰهَا فَجَآءَهَا بَأْسُنَا بَيَٰتًا أَوْ هُمْ قَآئِلُونَ<br>فَمَا كَانَ دَعْوَىٰهُمْ إِذْ جَآءَهُم بَأْسُنَآ إِلَّآ أَن قَالُوٓا۟ إِنَّا كُنَّا ظَٰلِمِينَ ۝ هَذِهِ السُّورَةُ تَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ نُوحٍ وَمُوسَىٰ وَتُحَذِّرُ مِنَ الْعَذَابِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim Sad. A Book revealed to you—so let there be no discomfort in your heart from it—that you may warn thereby and as a reminder to the believers. Follow what has been revealed to you from your Lord and do not follow other than Him as allies. Little do you remember. And how many a city We destroyed, and Our punishment came to them at night or while they were sleeping at noon.<br>Then their plea when Our punishment came to them was only that they said, 'Indeed, we were wrongdoers.' This surah narrates the stories of prophets like Noah and Moses, warning against the punishment for disbelief.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim Sad. Un Livre qui t’a été révélé—qu’il n’y ait donc pas de gêne dans ton cœur à cause de lui—afin que tu avertisses par lui et qu’il soit un rappel pour les croyants. Suivez ce qui vous a été révélé de votre Seigneur et ne suivez pas d’autres alliés en dehors de Lui. Peu vous vous souvenez. Combien de cités avons-Nous détruites, et Notre châtiment leur est venu la nuit ou pendant qu’ils faisaient la sieste à midi.<br>Leur seule plainte, lorsque Notre châtiment les atteignit, fut de dire : 'En vérité, nous étions injustes.' Cette sourate raconte les histoires de prophètes comme Noé et Moïse, mettant en garde contre le châtiment pour l’incroyance."
    },
    22: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَسْـَٔلُونَكَ عَنِ ٱلْأَنفَالِ ۖ قُلِ ٱلْأَنفَالُ لِلَّهِ وَٱلرَّسُولِ ۖ فَٱتَّقُوا۟ ٱللَّهَ وَأَصْلِحُوا۟ ذَاتَ بَيْنِكُمْ ۖ وَأَطِيعُوا۟ ٱللَّهَ وَرَسُولَهُۥٓ إِن كُنتُم مُّؤْمِنِينَ ۝ إِنَّمَا ٱلْمُؤْمِنُونَ ٱلَّذِينَ إِذَا ذُكِرَ ٱللَّهُ وَجِلَتْ قُلُوبُهُمْ وَإِذَا تُلِيَتْ عَلَيْهِمْ ءَايَٰتُهُۥ زَادَتْهُمْ إِيمَٰنًا<br>وَعَلَىٰ رَبِّهِمْ يَتَوَكَّلُونَ ۝ هَذِهِ السُّورَةُ تَتَحَدَّثُ عَنْ غَنَائِمِ الْحَرْبِ وَمَعْرَكَةِ بَدْرٍ وَتُعَلِّمُ الْمُؤْمِنِينَ الصَّبْرَ وَالطَّاعَةَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>They ask you about the spoils of war. Say, 'The spoils belong to Allah and the Messenger, so fear Allah and set right the matters between you, and obey Allah and His Messenger if you are believers.' The true believers are those whose hearts tremble when Allah is mentioned, and when His verses are recited to them, it increases their faith.<br>And they rely upon their Lord. This surah discusses the spoils of war and the Battle of Badr, teaching the believers patience and obedience to Allah and His Messenger.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ils te questionnent au sujet des butins. Dis : 'Les butins appartiennent à Allah et au Messager, alors craignez Allah et réglez vos différends, et obéissez à Allah et à Son Messager si vous êtes croyants.' Les vrais croyants sont ceux dont les cœurs frémissent quand Allah est mentionné, et lorsque Ses versets leur sont récités, cela augmente leur foi.<br>Et ils s’en remettent à leur Seigneur. Cette sourate parle des butins de guerre et de la bataille de Badr, enseignant aux croyants la patience et l’obéissance à Allah et à Son Messager."
    },
    23: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>بَرَاءَةٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلَّذِينَ عَٰهَدتُّم مِّنَ ٱلْمُشْرِكِينَ ۝ فَسِيحُوا۟ فِى ٱلْأَرْضِ أَرْبَعَةَ أَشْهُرٍ وَٱعْلَمُوٓا۟ أَنَّكُمْ غَيْرُ مُعْجِزِى ٱللَّهِ ۖ وَأَنَّ ٱللَّهَ مُخْزِى ٱلْكَٰفِرِينَ ۝ وَأَذَٰنٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلنَّاسِ يَوْمَ ٱلْحَجِّ ٱلْأَكْبَرِ<br>أَنَّ ٱللَّهَ بَرِىٓءٌ مِّنَ ٱلْمُشْرِكِينَ ۙ وَرَسُولُهُۥ ۚ هَذِهِ السُّورَةُ تُعْلِنُ انْتِهَاءَ الْعَهْدِ مَعَ الْمُشْرِكِينَ وَتُحَدِّدُ أَحْكَامَ الْجِهَادِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>A declaration of disassociation from Allah and His Messenger to those with whom you had made a treaty among the polytheists. So travel freely in the land for four months but know that you cannot escape Allah and that Allah will disgrace the disbelievers. And an announcement from Allah and His Messenger to the people on the day of the greater pilgrimage.<br>That Allah is free from the polytheists, and so is His Messenger. This surah declares the end of treaties with the polytheists and outlines the rules of jihad, emphasizing the importance of upholding faith.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Une déclaration de rupture de la part d’Allah et de Son Messager envers ceux des polythéistes avec lesquels vous aviez conclu un pacte. Parcourez librement la terre pendant quatre mois, mais sachez que vous ne saurez échapper à Allah et qu’Allah couvrira d’opprobre les mécréants. Et un appel d’Allah et de Son Messager aux gens le jour du grand pèlerinage.<br>Qu’Allah est dégagé des polythéistes, ainsi que Son Messager. Cette sourate annonce la fin des pactes avec les polythéistes et établit les règles du jihad, soulignant l’importance de maintenir la foi."
    },
    24: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ٱلْحَكِيمِ ۝ أَكَانَ لِلنَّاسِ عَجَبًا أَنْ أَوْحَيْنَآ إِلَىٰ رَجُلٍ مِّنْهُمْ أَنْ أَنذِرِ ٱلنَّاسَ وَبَشِّرِ ٱلَّذِينَ ءَامَنُوٓا۟ أَنَّ لَهُمْ قَدَمَ صِدْقٍ عِندَ رَبِّهِمْ ۗ قَالَ ٱلْكَٰفِرُونَ إِنَّ هَٰذَا لَسَٰحِرٌ مُّبِينٌ ۝ إِنَّ رَبَّكُمُ ٱللَّهُ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ فِى سِتَّةِ أَيَّامٍ<br>ثُمَّ ٱسْتَوَىٰ عَلَى ٱلْعَرْشِ ۖ يُدَبِّرُ ٱلْأَمْرَ ۖ مَا مِن شَفِيعٍ إِلَّا مِنۢ بَعْدِ إِذْنِهِۦ ۚ ذَٰلِكُمُ ٱللَّهُ رَبُّكُمْ فَٱعْبُدُوهُ ۚ هَذِهِ السُّورَةُ تُسَمَّى يُونُسْ وَتُرَكِّزُ عَلَىٰ دَعْوَةِ الْأَنْبِيَاءِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the wise Book. Was it a wonder to the people that We revealed to a man from among them that he should warn the people and give good tidings to those who believe that they will have a noble reward with their Lord? The disbelievers say, 'Indeed, this is an obvious magician.' Indeed, your Lord is Allah, who created the heavens and the earth in six days.<br>Then He established Himself on the Throne, arranging the matter; there is no intercessor except after His permission. That is Allah, your Lord, so worship Him. This surah, named Yunus, focuses on the mission of the prophets and their call to worship Allah alone.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre sage. Est-ce une chose étonnante pour les gens que Nous ayons révélé à un homme d’entre eux de mettre en garde les gens et d’annoncer la bonne nouvelle à ceux qui croient qu’ils auront une belle récompense auprès de leur Seigneur ? Les mécréants disent : 'Ceci est un magicien manifeste.' En vérité, votre Seigneur est Allah, qui a créé les cieux et la terre en six jours.<br>Puis Il S’est établi sur le Trône, gérant l’ordre ; il n’y a d’intercesseur qu’avec Sa permission. Tel est Allah, votre Seigneur, alors adorez-Le. Cette sourate, nommée Yunus, met l’accent sur la mission des prophètes et leur appel à adorer Allah seul."
    },
    25: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ كِتَٰبٌ أُحْكِمَتْ ءَايَٰتُهُۥ ثُمَّ فُصِّلَتْ مِن لَّدُنْ حَكِيمٍ خَبِيرٍ ۝ أَلَّا تَعْبُدُوٓا۟ إِلَّا ٱللَّهَ ۚ إِنَّنِى لَكُم مِّنْهُ نَذِيرٌ وَبَشِيرٌ ۝ وَأَنِ ٱسْتَغْفِرُوا۟ رَبَّكُمْ ثُمَّ تُوبُوٓا۟ إِلَيْهِ يُمَتِّعْكُم مَّتَٰعًا حَسَنًا إِلَىٰٓ أَجَلٍ مُّسَمًّى وَيُؤْتِ كُلَّ ذِى فَضْلٍ فَضْلَهُۥ ۖ وَإِن تَوَلَّوْا۟ فَإِنِّىٓ أَخَافُ عَلَيْكُمْ عَذَابَ يَوْمٍ كَبِيرٍ<br>إِلَى ٱللَّهِ مَرْجِعُكُمْ ۖ وَهُوَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ ۝ هَذِهِ السُّورَةُ تُسَمَّى هُودٍ وَتَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ نُوحٍ وَهُودٍ وَصَالِحٍ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. A Book whose verses have been detailed, then distinguished from One who is Wise and Acquainted. [Saying], 'Worship none but Allah. Indeed, I am to you from Him a warner and a bringer of good tidings.' And [saying], 'Seek forgiveness of your Lord and repent to Him, and He will let you enjoy a good provision for a specified term and give every doer of favor his favor. But if you turn away, then I fear for you the punishment of a great Day.'<br>To Allah is your return, and He is over all things competent. This surah, named Hud, narrates the stories of prophets like Noah, Hud, and Salih, highlighting their warnings and the consequences of disbelief.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Un Livre dont les versets ont été détaillés, puis distingués, de la part d’un Sage, parfaitement Informé. [Disant] : 'N’adorez qu’Allah. En vérité, je suis pour vous, de Sa part, un avertisseur et un annonciateur de bonne nouvelle.' Et [disant] : 'Demandez pardon à votre Seigneur et repentez-vous à Lui, Il vous fera jouir d’une belle provision jusqu’à un terme fixé et accordera à tout homme de mérite sa récompense. Mais si vous vous détournez, je crains pour vous le châtiment d’un jour terrible.'<br>C’est vers Allah que vous retournerez, et Il est capable de toute chose. Cette sourate, nommée Hud, raconte les histoires des prophètes comme Noé, Hud et Salih, mettant en lumière leurs avertissements et les conséquences de l’incroyance."
    },
    26: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ٱلْمُبِينِ ۝ إِنَّآ أَنزَلْنَٰهُ قُرْءَانًا عَرَبِيًّا لَّعَلَّكُمْ تَعْقِلُونَ ۝ نَحْنُ نَقُصُّ عَلَيْكَ أَحْسَنَ ٱلْقَصَصِ بِمَآ أَوْحَيْنَآ إِلَيْكَ هَٰذَا ٱلْقُرْءَانَ وَإِن كُنتَ مِن قَبْلِهِۦ لَمِنَ ٱلْغَٰفِلِينَ ۝ إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَٰٓأَبَتِ إِنِّى رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًا وَٱلشَّمْسَ وَٱلْقَمَرَ رَأَيْتُهُمْ لِى سَٰجِدِينَ<br>قَالَ يَٰبُنَىَّ لَا تَقْصُصْ رُءْيَاكَ عَلَىٰٓ إِخْوَتِكَ فَيَكِيدُوا۟ لَكَ كَيْدًا ۖ إِنَّ ٱلشَّيْطَٰنَ لِلْإِنسَٰنِ عَدُوٌّ مُّبِينٌ ۝ هَذِهِ السُّورَةُ تَحْكِي قِصَّةَ يُوسُفَ عَلَيْهِ السَّلَامُ وَتُعَلِّمُ الصَّبْرَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the clear Book. Indeed, We have sent it down as an Arabic Quran that you might understand. We relate to you the best of stories in what We have revealed to you of this Quran, although you were, before it, among the unaware. When Joseph said to his father, 'O my father, indeed I have seen eleven stars and the sun and the moon; I saw them prostrating to me.'<br>He said, 'O my son, do not relate your vision to your brothers or they will contrive against you a plan. Indeed, Satan is to man a clear enemy.' This surah tells the story of Prophet Joseph (Yusuf) and teaches the virtue of patience in the face of trials.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre clair. En vérité, Nous l’avons fait descendre en un Coran arabe afin que vous raisonniez. Nous te racontons la plus belle des histoires par ce que Nous t’avons révélé de ce Coran, bien que tu fusses auparavant parmi les ignorants. Lorsque Joseph dit à son père : 'Ô mon père, j’ai vu onze étoiles, le soleil et la lune ; je les ai vus se prosterner devant moi.'<br>Il dit : 'Ô mon fils, ne raconte pas ta vision à tes frères, de peur qu’ils ne trament un complot contre toi. En vérité, Satan est pour l’homme un ennemi déclaré.' Cette sourate raconte l’histoire du prophète Joseph (Yusuf) et enseigne la vertu de la patience face aux épreuves."
    },
    27: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>المر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ۗ وَٱلَّذِىٓ أُنزِلَ إِلَيْكَ مِن رَّبِّكَ ٱلْحَقُّ وَلَٰكِنَّ أَكْثَرَ ٱلنَّاسِ لَا يُؤْمِنُونَ ۝ ٱللَّهُ ٱلَّذِى رَفَعَ ٱلسَّمَٰوَٰتِ بِغَيْرِ عَمَدٍ تَرَوْنَهَا ۖ ثُمَّ ٱسْتَوَىٰ عَلَى ٱلْعَرْشِ ۖ وَسَخَّرَ ٱلشَّمْسَ وَٱلْقَمَرَ ۖ كُلٌّ يَجْرِى لِأَجَلٍ مُّسَمًّى ۚ يُدَبِّرُ ٱلْأَمْرَ يُفَصِّلُ ٱلْءَايَٰتِ لَعَلَّكُم بِلِقَآءِ رَبِّكُمْ تُوقِنُونَ<br>وَهُوَ ٱلَّذِى مَدَّ ٱلْأَرْضَ وَجَعَلَ فِيهَا رَوَٰسِىَ وَأَنْهَٰرًا ۖ هَذِهِ السُّورَةُ تُسَمَّى الرَّعْدِ وَتُرَكِّزُ عَلَىٰ عَظَمَةِ خَلْقِ ٱللَّهِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim Ra. These are the verses of the Book. And what has been revealed to you from your Lord is the truth, but most of the people do not believe. Allah is the One who raised the heavens without pillars that you can see; then He established Himself on the Throne and subjected the sun and the moon, each running its course for a specified term. He arranges the matter; He details the signs that you may be certain of the meeting with your Lord.<br>And it is He who spread the earth and placed therein firmly set mountains and rivers. This surah, named Ar-Ra'd (The Thunder), focuses on the greatness of Allah's creation and His signs in the universe.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim Ra. Ce sont les versets du Livre. Et ce qui t’a été révélé de ton Seigneur est la vérité, mais la plupart des gens ne croient pas. Allah est Celui qui a élevé les cieux sans piliers visibles ; puis Il S’est établi sur le Trône et a soumis le soleil et la lune, chacun courant jusqu’à un terme fixé. Il gère l’ordre et détaille les signes afin que vous soyez certains de la rencontre avec votre Seigneur.<br>Et c’est Lui qui a étendu la terre et y a placé des montagnes immobiles et des rivières. Cette sourate, nommée Ar-Ra'd (Le Tonnerre), met l’accent sur la grandeur de la création d’Allah et Ses signes dans l’univers."
    },
    28: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ كِتَٰبٌ أَنزَلْنَٰهُ إِلَيْكَ لِتُخْرِجَ ٱلنَّاسَ مِنَ ٱلظُّلُمَٰتِ إِلَى ٱلنُّورِ بِإِذْنِ رَبِّهِمْ إِلَىٰ صِرَٰطِ ٱلْعَزِيزِ ٱلْحَمِيدِ ۝ ٱللَّهِ ٱلَّذِى لَهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ وَوَيْلٌ لِّلْكَٰفِرِينَ مِنْ عَذَابٍ شَدِيدٍ ۝ ٱلَّذِينَ يَسْتَحِبُّونَ ٱلْحَيَوٰةَ ٱلدُّنْيَا عَلَى ٱلْءَاخِرَةِ وَيَصُدُّونَ عَن سَبِيلِ ٱللَّهِ وَيَبْغُونَهَا عِوَجًا ۚ أُو۟لَٰٓئِكَ فِى ضَلَٰلٍۢ بَعِيدٍ<br>وَمَآ أَرْسَلْنَا مِن رَّسُولٍ إِلَّا بِلِسَانِ قَوْمِهِۦ لِيُبَيِّنَ لَهُمْ ۖ هَذِهِ السُّورَةُ تُسَمَّى إِبْرَاهِيمَ وَتُرَكِّزُ عَلَىٰ دَعْوَةِ الْأَنْبِيَاءِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. A Book which We have revealed to you that you might bring mankind out of darknesses into the light by the permission of their Lord—to the path of the Exalted in Might, the Praiseworthy—Allah, to whom belongs whatever is in the heavens and whatever is on the earth. And woe to the disbelievers from a severe punishment—the ones who prefer the worldly life over the Hereafter and avert people from the way of Allah, seeking to make it crooked. Those are in far error.<br>And We did not send any messenger except in the language of his people to state clearly for them. This surah, named Ibrahim, focuses on the call of the prophets to guide people to the truth.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Un Livre que Nous t’avons révélé afin que tu fasses sortir les gens des ténèbres vers la lumière, par la permission de leur Seigneur, vers le chemin du Tout-Puissant, Digne de louange—Allah, à qui appartient tout ce qui est dans les cieux et sur la terre. Et malheur aux mécréants à cause d’un châtiment sévère—ceux qui préfèrent la vie d’ici-bas à l’au-delà, qui détournent les gens du chemin d’Allah et cherchent à le rendre tortueux. Ceux-là sont dans un égarement profond.<br>Et Nous n’avons envoyé de messager qu’avec la langue de son peuple afin qu’il leur explique clairement. Cette sourate, nommée Ibrahim, met l’accent sur l’appel des prophètes à guider les gens vers la vérité."
    },
    29: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ وَقُرْءَانٍ مُّبِينٍ ۝ رُّبَمَا يَوَدُّ ٱلَّذِينَ كَفَرُوٓا۟ لَوْ كَانُوا۟ مُسْلِمِينَ ۝ ذَرْهُمْ يَأْكُلُوا۟ وَيَتَمَتَّعُوا۟ وَيُلْهِهِمُ ٱلْأَمَلُ ۖ فَسَوْفَ يَعْلَمُونَ ۝ وَمَآ أَهْلَكْنَا مِن قَرْيَةٍ إِلَّا وَلَهَا كِتَٰبٌ مَّعْلُومٌ ۝ مَّا تَسْبِقُ مِنْ أُمَّةٍ أَجَلَهَا وَمَا يَسْتَـْٔخِرُونَ<br>وَقَالُوا۟ يَٰٓأَيُّهَا ٱلَّذِى نُزِّلَ عَلَيْهِ ٱلذِّكْرُ إِنَّكَ لَمَجْنُونٌ ۖ هَذِهِ السُّورَةُ تُسَمَّى الْحِجْرِ وَتُرَكِّزُ عَلَىٰ قِصَصِ الْأَقْوَامِ الْمُهْلَكَةِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the Book and a clear Quran. Perhaps those who disbelieve will wish that they had been Muslims. Let them eat and enjoy themselves and be diverted by false hope, for they will come to know. And We did not destroy any city but that it had a known decree. No nation can advance its term, nor can they delay it.<br>And they say, 'O you upon whom the message has been sent down, indeed you are mad.' This surah, named Al-Hijr, focuses on the stories of destroyed nations and serves as a warning to those who reject the truth.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre et d’un Coran clair. Peut-être que ceux qui mécroient souhaiteraient avoir été musulmans. Laisse-les manger, jouir et se laisser distraire par de faux espoirs, car bientôt ils sauront. Nous n’avons détruit aucune cité sans qu’elle ait eu un décret connu. Aucune nation ne peut devancer son terme ni le retarder.<br>Et ils disent : 'Ô toi sur qui le Rappel a été descendu, tu es certes un fou.' Cette sourate, nommée Al-Hijr, met l’accent sur les histoires des peuples détruits et sert d’avertissement à ceux qui rejettent la vérité."
    },
      30: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>بَرَاءَةٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلَّذِينَ عَٰهَدتُّم مِّنَ ٱلْمُشْرِكِينَ ۝ فَسِيحُوا۟ فِى ٱلْأَرْضِ أَرْبَعَةَ أَشْهُرٍ وَٱعْلَمُوٓا۟ أَنَّكُمْ غَيْرُ مُعْجِزِى ٱللَّهِ ۖ وَأَنَّ ٱللَّهَ مُخْزِى ٱلْكَٰفِرِينَ ۝ وَأَذَٰنٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلنَّاسِ يَوْمَ ٱلْحَجِّ ٱلْأَكْبَرِ<br>أَنَّ ٱللَّهَ بَرِىٓءٌ مِّنَ ٱلْمُشْرِكِينَ ۙ وَرَسُولُهُۥ ۚ هَذِهِ السُّورَةُ تُعْلِنُ انْتِهَاءَ الْعَهْدِ مَعَ الْمُشْرِكِينَ وَتُحَدِّدُ أَحْكَامَ الْجِهَادِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>A declaration of disassociation from Allah and His Messenger to those with whom you had made a treaty among the polytheists. So travel freely in the land for four months but know that you cannot escape Allah and that Allah will disgrace the disbelievers. And an announcement from Allah and His Messenger to the people on the day of the greater pilgrimage.<br>That Allah is free from the polytheists, and so is His Messenger. This surah declares the end of treaties with the polytheists and outlines the rules of jihad, emphasizing the importance of upholding faith.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Une déclaration de rupture de la part d’Allah et de Son Messager envers ceux des polythéistes avec lesquels vous aviez conclu un pacte. Parcourez librement la terre pendant quatre mois, mais sachez que vous ne saurez échapper à Allah et qu’Allah couvrira d’opprobre les mécréants. Et un appel d’Allah et de Son Messager aux gens le jour du grand pèlerinage.<br>Qu’Allah est dégagé des polythéistes, ainsi que Son Messager. Cette sourate annonce la fin des pactes avec les polythéistes et établit les règles du jihad, soulignant l’importance de maintenir la foi."
    },
    31: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ٱلْحَكِيمِ ۝ أَكَانَ لِلنَّاسِ عَجَبًا أَنْ أَوْحَيْنَآ إِلَىٰ رَجُلٍ مِّنْهُمْ أَنْ أَنذِرِ ٱلنَّاسَ وَبَشِّرِ ٱلَّذِينَ ءَامَنُوٓا۟ أَنَّ لَهُمْ قَدَمَ صِدْقٍ عِندَ رَبِّهِمْ ۗ قَالَ ٱلْكَٰفِرُونَ إِنَّ هَٰذَا لَسَٰحِرٌ مُّبِينٌ ۝ إِنَّ رَبَّكُمُ ٱللَّهُ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ فِى سِتَّةِ أَيَّامٍ<br>ثُمَّ ٱسْتَوَىٰ عَلَى ٱلْعَرْشِ ۖ يُدَبِّرُ ٱلْأَمْرَ ۖ مَا مِن شَفِيعٍ إِلَّا مِنۢ بَعْدِ إِذْنِهِۦ ۚ ذَٰلِكُمُ ٱللَّهُ رَبُّكُمْ فَٱعْبُدُوهُ ۚ هَذِهِ السُّورَةُ تُسَمَّى يُونُسْ وَتُرَكِّزُ عَلَىٰ دَعْوَةِ الْأَنْبِيَاءِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the wise Book. Was it a wonder to the people that We revealed to a man from among them that he should warn the people and give good tidings to those who believe that they will have a noble reward with their Lord? The disbelievers say, 'Indeed, this is an obvious magician.' Indeed, your Lord is Allah, who created the heavens and the earth in six days.<br>Then He established Himself on the Throne, arranging the matter; there is no intercessor except after His permission. That is Allah, your Lord, so worship Him. This surah, named Yunus, focuses on the mission of the prophets and their call to worship Allah alone.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre sage. Est-ce une chose étonnante pour les gens que Nous ayons révélé à un homme d’entre eux de mettre en garde les gens et d’annoncer la bonne nouvelle à ceux qui croient qu’ils auront une belle récompense auprès de leur Seigneur ? Les mécréants disent : 'Ceci est un magicien manifeste.' En vérité, votre Seigneur est Allah, qui a créé les cieux et la terre en six jours.<br>Puis Il S’est établi sur le Trône, gérant l’ordre ; il n’y a d’intercesseur qu’avec Sa permission. Tel est Allah, votre Seigneur, alors adorez-Le. Cette sourate, nommée Yunus, met l’accent sur la mission des prophètes et leur appel à adorer Allah seul."
    },
    32: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ كِتَٰبٌ أُحْكِمَتْ ءَايَٰتُهُۥ ثُمَّ فُصِّلَتْ مِن لَّدُنْ حَكِيمٍ خَبِيرٍ ۝ أَلَّا تَعْبُدُوٓا۟ إِلَّا ٱللَّهَ ۚ إِنَّنِى لَكُم مِّنْهُ نَذِيرٌ وَبَشِيرٌ ۝ وَأَنِ ٱسْتَغْفِرُوا۟ رَبَّكُمْ ثُمَّ تُوبُوٓا۟ إِلَيْهِ يُمَتِّعْكُم مَّتَٰعًا حَسَنًا إِلَىٰٓ أَجَلٍ مُّسَمًّى وَيُؤْتِ كُلَّ ذِى فَضْلٍ فَضْلَهُۥ ۖ وَإِن تَوَلَّوْا۟ فَإِنِّىٓ أَخَافُ عَلَيْكُمْ عَذَابَ يَوْمٍ كَبِيرٍ<br>إِلَى ٱللَّهِ مَرْجِعُكُمْ ۖ وَهُوَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ ۝ هَذِهِ السُّورَةُ تُسَمَّى هُودٍ وَتَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ نُوحٍ وَهُودٍ وَصَالِحٍ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. A Book whose verses have been detailed, then distinguished from One who is Wise and Acquainted. [Saying], 'Worship none but Allah. Indeed, I am to you from Him a warner and a bringer of good tidings.' And [saying], 'Seek forgiveness of your Lord and repent to Him, and He will let you enjoy a good provision for a specified term and give every doer of favor his favor. But if you turn away, then I fear for you the punishment of a great Day.'<br>To Allah is your return, and He is over all things competent. This surah, named Hud, narrates the stories of prophets like Noah, Hud, and Salih, highlighting their warnings and the consequences of disbelief.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Un Livre dont les versets ont été détaillés, puis distingués, de la part d’un Sage, parfaitement Informé. [Disant] : 'N’adorez qu’Allah. En vérité, je suis pour vous, de Sa part, un avertisseur et un annonciateur de bonne nouvelle.' Et [disant] : 'Demandez pardon à votre Seigneur et repentez-vous à Lui, Il vous fera jouir d’une belle provision jusqu’à un terme fixé et accordera à tout homme de mérite sa récompense. Mais si vous vous détournez, je crains pour vous le châtiment d’un jour terrible.'<br>C’est vers Allah que vous retournerez, et Il est capable de toute chose. Cette sourate, nommée Hud, raconte les histoires des prophètes comme Noé, Hud et Salih, mettant en lumière leurs avertissements et les conséquences de l’incroyance."
    },
    33: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ٱلْمُبِينِ ۝ إِنَّآ أَنزَلْنَٰهُ قُرْءَانًا عَرَبِيًّا لَّعَلَّكُمْ تَعْقِلُونَ ۝ نَحْنُ نَقُصُّ عَلَيْكَ أَحْسَنَ ٱلْقَصَصِ بِمَآ أَوْحَيْنَآ إِلَيْكَ هَٰذَا ٱلْقُرْءَانَ وَإِن كُنتَ مِن قَبْلِهِۦ لَمِنَ ٱلْغَٰفِلِينَ ۝ إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَٰٓأَبَتِ إِنِّى رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًا وَٱلشَّمْسَ وَٱلْقَمَرَ رَأَيْتُهُمْ لِى سَٰجِدِينَ<br>قَالَ يَٰبُنَىَّ لَا تَقْصُصْ رُءْيَاكَ عَلَىٰٓ إِخْوَتِكَ فَيَكِيدُوا۟ لَكَ كَيْدًا ۖ إِنَّ ٱلشَّيْطَٰنَ لِلْإِنسَٰنِ عَدُوٌّ مُّبِينٌ ۝ هَذِهِ السُّورَةُ تَحْكِي قِصَّةَ يُوسُفَ عَلَيْهِ السَّلَامُ وَتُعَلِّمُ الصَّبْرَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the clear Book. Indeed, We have sent it down as an Arabic Quran that you might understand. We relate to you the best of stories in what We have revealed to you of this Quran, although you were, before it, among the unaware. When Joseph said to his father, 'O my father, indeed I have seen eleven stars and the sun and the moon; I saw them prostrating to me.'<br>He said, 'O my son, do not relate your vision to your brothers or they will contrive against you a plan. Indeed, Satan is to man a clear enemy.' This surah tells the story of Prophet Joseph (Yusuf) and teaches the virtue of patience in the face of trials.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre clair. En vérité, Nous l’avons fait descendre en un Coran arabe afin que vous raisonniez. Nous te racontons la plus belle des histoires par ce que Nous t’avons révélé de ce Coran, bien que tu fusses auparavant parmi les ignorants. Lorsque Joseph dit à son père : 'Ô mon père, j’ai vu onze étoiles, le soleil et la lune ; je les ai vus se prosterner devant moi.'<br>Il dit : 'Ô mon fils, ne raconte pas ta vision à tes frères, de peur qu’ils ne trament un complot contre toi. En vérité, Satan est pour l’homme un ennemi déclaré.' Cette sourate raconte l’histoire du prophète Joseph (Yusuf) et enseigne la vertu de la patience face aux épreuves."
    },
    34: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>المر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ ۗ وَٱلَّذِىٓ أُنزِلَ إِلَيْكَ مِن رَّبِّكَ ٱلْحَقُّ وَلَٰكِنَّ أَكْثَرَ ٱلنَّاسِ لَا يُؤْمِنُونَ ۝ ٱللَّهُ ٱلَّذِى رَفَعَ ٱلسَّمَٰوَٰتِ بِغَيْرِ عَمَدٍ تَرَوْنَهَا ۖ ثُمَّ ٱسْتَوَىٰ عَلَى ٱلْعَرْشِ ۖ وَسَخَّرَ ٱلشَّمْسَ وَٱلْقَمَرَ ۖ كُلٌّ يَجْرِى لِأَجَلٍ مُّسَمًّى ۚ يُدَبِّرُ ٱلْأَمْرَ يُفَصِّلُ ٱلْءَايَٰتِ لَعَلَّكُم بِلِقَآءِ رَبِّكُمْ تُوقِنُونَ<br>وَهُوَ ٱلَّذِى مَدَّ ٱلْأَرْضَ وَجَعَلَ فِيهَا رَوَٰسِىَ وَأَنْهَٰرًا ۖ هَذِهِ السُّورَةُ تُسَمَّى الرَّعْدِ وَتُرَكِّزُ عَلَىٰ عَظَمَةِ خَلْقِ ٱللَّهِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim Ra. These are the verses of the Book. And what has been revealed to you from your Lord is the truth, but most of the people do not believe. Allah is the One who raised the heavens without pillars that you can see; then He established Himself on the Throne and subjected the sun and the moon, each running its course for a specified term. He arranges the matter; He details the signs that you may be certain of the meeting with your Lord.<br>And it is He who spread the earth and placed therein firmly set mountains and rivers. This surah, named Ar-Ra'd (The Thunder), focuses on the greatness of Allah's creation and His signs in the universe.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim Ra. Ce sont les versets du Livre. Et ce qui t’a été révélé de ton Seigneur est la vérité, mais la plupart des gens ne croient pas. Allah est Celui qui a élevé les cieux sans piliers visibles ; puis Il S’est établi sur le Trône et a soumis le soleil et la lune, chacun courant jusqu’à un terme fixé. Il gère l’ordre et détaille les signes afin que vous soyez certains de la rencontre avec votre Seigneur.<br>Et c’est Lui qui a étendu la terre et y a placé des montagnes immobiles et des rivières. Cette sourate, nommée Ar-Ra'd (Le Tonnerre), met l’accent sur la grandeur de la création d’Allah et Ses signes dans l’univers."
    },
    35: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ كِتَٰبٌ أَنزَلْنَٰهُ إِلَيْكَ لِتُخْرِجَ ٱلنَّاسَ مِنَ ٱلظُّلُمَٰتِ إِلَى ٱلنُّورِ بِإِذْنِ رَبِّهِمْ إِلَىٰ صِرَٰطِ ٱلْعَزِيزِ ٱلْحَمِيدِ ۝ ٱللَّهِ ٱلَّذِى لَهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ وَوَيْلٌ لِّلْكَٰفِرِينَ مِنْ عَذَابٍ شَدِيدٍ ۝ ٱلَّذِينَ يَسْتَحِبُّونَ ٱلْحَيَوٰةَ ٱلدُّنْيَا عَلَى ٱلْءَاخِرَةِ وَيَصُدُّونَ عَن سَبِيلِ ٱللَّهِ وَيَبْغُونَهَا عِوَجًا ۚ أُو۟لَٰٓئِكَ فِى ضَلَٰلٍۢ بَعِيدٍ<br>وَمَآ أَرْسَلْنَا مِن رَّسُولٍ إِلَّا بِلِسَانِ قَوْمِهِۦ لِيُبَيِّنَ لَهُمْ ۖ هَذِهِ السُّورَةُ تُسَمَّى إِبْرَاهِيمَ وَتُرَكِّزُ عَلَىٰ دَعْوَةِ الْأَنْبِيَاءِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. A Book which We have revealed to you that you might bring mankind out of darknesses into the light by the permission of their Lord—to the path of the Exalted in Might, the Praiseworthy—Allah, to whom belongs whatever is in the heavens and whatever is on the earth. And woe to the disbelievers from a severe punishment—the ones who prefer the worldly life over the Hereafter and avert people from the way of Allah, seeking to make it crooked. Those are in far error.<br>And We did not send any messenger except in the language of his people to state clearly for them. This surah, named Ibrahim, focuses on the call of the prophets to guide people to the truth.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Un Livre que Nous t’avons révélé afin que tu fasses sortir les gens des ténèbres vers la lumière, par la permission de leur Seigneur, vers le chemin du Tout-Puissant, Digne de louange—Allah, à qui appartient tout ce qui est dans les cieux et sur la terre. Et malheur aux mécréants à cause d’un châtiment sévère—ceux qui préfèrent la vie d’ici-bas à l’au-delà, qui détournent les gens du chemin d’Allah et cherchent à le rendre tortueux. Ceux-là sont dans un égarement profond.<br>Et Nous n’avons envoyé de messager qu’avec la langue de son peuple afin qu’il leur explique clairement. Cette sourate, nommée Ibrahim, met l’accent sur l’appel des prophètes à guider les gens vers la vérité."
    },
    36: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الر ۚ تِلْكَ آيَٰتُ ٱلْكِتَٰبِ وَقُرْءَانٍ مُّبِينٍ ۝ رُّبَمَا يَوَدُّ ٱلَّذِينَ كَفَرُوٓا۟ لَوْ كَانُوا۟ مُسْلِمِينَ ۝ ذَرْهُمْ يَأْكُلُوا۟ وَيَتَمَتَّعُوا۟ وَيُلْهِهِمُ ٱلْأَمَلُ ۖ فَسَوْفَ يَعْلَمُونَ ۝ وَمَآ أَهْلَكْنَا مِن قَرْيَةٍ إِلَّا وَلَهَا كِتَٰبٌ مَّعْلُومٌ ۝ مَّا تَسْبِقُ مِنْ أُمَّةٍ أَجَلَهَا وَمَا يَسْتَـْٔخِرُونَ<br>وَقَالُوا۟ يَٰٓأَيُّهَا ٱلَّذِى نُزِّلَ عَلَيْهِ ٱلذِّكْرُ إِنَّكَ لَمَجْنُونٌ ۖ هَذِهِ السُّورَةُ تُسَمَّى الْحِجْرِ وَتُرَكِّزُ عَلَىٰ قِصَصِ الْأَقْوَامِ الْمُهْلَكَةِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Ra. These are the verses of the Book and a clear Quran. Perhaps those who disbelieve will wish that they had been Muslims. Let them eat and enjoy themselves and be diverted by false hope, for they will come to know. And We did not destroy any city but that it had a known decree. No nation can advance its term, nor can they delay it.<br>And they say, 'O you upon whom the message has been sent down, indeed you are mad.' This surah, named Al-Hijr, focuses on the stories of destroyed nations and serves as a warning to those who reject the truth.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Ra. Ce sont les versets du Livre et d’un Coran clair. Peut-être que ceux qui mécroient souhaiteraient avoir été musulmans. Laisse-les manger, jouir et se laisser distraire par de faux espoirs, car bientôt ils sauront. Nous n’avons détruit aucune cité sans qu’elle ait eu un décret connu. Aucune nation ne peut devancer son terme ni le retarder.<br>Et ils disent : 'Ô toi sur qui le Rappel a été descendu, tu es certes un fou.' Cette sourate, nommée Al-Hijr, met l’accent sur les histoires des peuples détruits et sert d’avertissement à ceux qui rejettent la vérité."
    },
  37: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الم ۝ ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ ۝ ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ ۝ وَٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلْءَاخِرَةِ هُمْ يُوقِنُونَ<br>أُو۟لَٰٓئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ ۝ هَذِهِ السُّورَةُ هِيَ أَطْوَلُ سُورَةٍ فِي الْقُرْآنِ وَتَحْتَوِي عَلَىٰ قِصَصٍ وَأَحْكَامٍ شَرْعِيَّةٍ تُعَلِّمُ الْمُسْلِمِينَ كَيْفَ يَعِيشُونَ حَيَاةً مُسْتَقِيمَةً.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim. This is the Book about which there is no doubt, a guidance for those conscious of Allah, who believe in the unseen, establish prayer, and spend out of what We have provided for them, and who believe in what has been revealed to you and what was revealed before you, and of the Hereafter they are certain.<br>Those are upon guidance from their Lord, and those are the successful. This surah, Al-Baqarah, is the longest in the Quran and contains stories and legal rulings, teaching Muslims how to live a righteous life.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim. Ceci est le Livre au sujet duquel il n'y a aucun doute, un guide pour ceux qui craignent Allah, qui croient en l'invisible, accomplissent la prière et dépensent de ce que Nous leur avons attribué, et qui croient en ce qui t'a été révélé et en ce qui a été révélé avant toi, et qui sont certains de l'au-delà.<br>Ceux-là sont sur une guidance de leur Seigneur, et ce sont eux qui réussissent. Cette sourate, Al-Baqarah, est la plus longue du Coran et contient des récits et des lois, enseignant aux musulmans comment mener une vie droite."
    },
    38: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>الم ۝ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۝ نَزَّلَ عَلَيْكَ ٱلْكِتَٰبَ بِٱلْحَقِّ مُصَدِّقًا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ ٱلتَّوْرَىٰةَ وَٱلْإِنجِيلَ ۝ مِن قَبْلُ هُدًى لِّلنَّاسِ وَأَنزَلَ ٱلْفُرْقَانَ ۝ إِنَّ ٱلَّذِينَ كَفَرُوا۟ بِآيَٰتِ ٱللَّهِ لَهُمْ عَذَابٌ شَدِيدٌ<br>وَٱللَّهُ عَزِيزٌ ذُو ٱنتِقَامٍ ۝ هَذِهِ السُّورَةُ تُسَمَّى آلَ عِمْرَانَ وَتَتَحَدَّثُ عَنْ قِصَصِ الْأَنْبِيَاءِ وَأَهْلِ الْكِتَابِ وَتُؤَكِّدُ عَلَىٰ أَهَمِّيَّةِ الإِيمَانِ بِٱللَّهِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim. Allah, there is no deity except Him, the Ever-Living, the Sustainer of existence. He has sent down upon you the Book in truth, confirming what was before it, and He revealed the Torah and the Gospel previously as guidance for the people, and He revealed the Criterion. Indeed, those who disbelieve in the signs of Allah will have a severe punishment.<br>And Allah is Exalted in Might, the Owner of Retribution. This surah, named Aal-E-Imran, speaks about the stories of the prophets and the People of the Book, emphasizing the importance of faith in Allah.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim. Allah, il n'y a de divinité sauf Lui, le Vivant, le Subsistant. Il a fait descendre sur toi le Livre en vérité, confirmant ce qui était avant lui, et Il a révélé la Torah et l'Évangile auparavant comme guidance pour les gens, et Il a révélé le Discernement. Certes, ceux qui mécroient aux signes d'Allah auront un châtiment sévère.<br>Et Allah est Tout-Puissant, Détenteur de la rétribution. Cette sourate, nommée Aal-E-Imran, parle des histoires des prophètes et des Gens du Livre, mettant en avant l'importance de la foi en Allah."
    },
    39: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَٰٓأَيُّهَا ٱلنَّاسُ ٱتَّقُوا۟ رَبَّكُمُ ٱلَّذِى خَلَقَكُم مِّن نَّفْسٍ وَٰحِدَةٍ وَخَلَقَ مِنْهَا زَوْجَهَا وَبَثَّ مِنْهُمَا رِجَالًا كَثِيرًا وَنِسَآءً ۝ وَٱتَّقُوا۟ ٱللَّهَ ٱلَّذِى تَسَآءَلُونَ بِهِۦ وَٱلْأَرْحَامَ ۝ إِنَّ ٱللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا<br>وَءَاتُوا۟ ٱلْيَتَٰمَىٰٓ أَمْوَٰلَهُمْ ۖ وَلَا تَتَبَدَّلُوا۟ ٱلْخَبِيثَ بِٱلطَّيِّبِ ۖ وَلَا تَأْكُلُوٓا۟ أَمْوَٰلَهُمْ إِلَىٰٓ أَمْوَٰلِكُمْ ۚ إِنَّهُۥ كَانَ حُوبًا كَبِيرًا ۝ هَذِهِ السُّورَةُ تُعْلِمُ الْمُسْلِمِينَ حُقُوقَ الْمَرْأَةِ وَالْيَتَامَىٰ وَتُؤَكِّدُ عَلَىٰ الْعَدْلِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>O mankind, fear your Lord, who created you from one soul and created from it its mate and dispersed from both of them many men and women. And fear Allah, through whom you ask one another, and the wombs. Indeed, Allah is ever, over you, an Observer.<br>And give to the orphans their properties and do not substitute the defective for the good. And do not consume their properties into your own. Indeed, that is a great sin. This surah teaches Muslims the rights of women and orphans and emphasizes justice.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ô hommes, craignez votre Seigneur qui vous a créés d'une seule âme et a créé d'elle son épouse, et a fait naître d'eux beaucoup d'hommes et de femmes. Craignez Allah au nom duquel vous vous implorez les uns les autres, ainsi que les liens de parenté. En vérité, Allah vous observe constamment.<br>Et donnez aux orphelins leurs biens, et ne substituez pas le mauvais au bon, et ne consommez pas leurs biens avec les vôtres, car cela est un grand péché. Cette sourate enseigne aux musulmans les droits des femmes et des orphelins et insiste sur la justice."
    },
    40: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ أَوْفُوا۟ بِٱلْعُقُودِ ۚ أُحِلَّتْ لَكُم بَهِيمَةُ ٱلْأَنْعَٰمِ إِلَّا مَا يُتْلَىٰ عَلَيْكُمْ غَيْرَ مُحِلِّى ٱلصَّيْدِ وَأَنتُمْ حُرُمٌ ۗ إِنَّ ٱللَّهَ يَحْكُمُ مَا يُرِيدُ ۝ يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ لَا تُحِلُّوا۟ شَعَٰٓئِرَ ٱللَّهِ وَلَا ٱلشَّهْرَ ٱلْحَرَامَ<br>وَلَا ٱلْهَدْىَ وَلَا ٱلْقَلَٰٓئِدَ وَلَآ ءَآمِّينَ ٱلْبَيْتَ ٱلْحَرَامَ ۖ يَبْتَغُونَ فَضْلًا مِّن رَّبِّهِمْ وَرِضْوَٰنًا ۗ هَذِهِ السُّورَةُ تَحْتَوِي عَلَىٰ أَحْكَامِ الْعُقُودِ وَالْحَلَالِ وَالْحَرَامِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>O you who have believed, fulfill your contracts. Lawful to you are the animals of grazing livestock except for that which is recited to you—hunting not being permitted while you are in the state of ihram. Indeed, Allah ordains what He intends. O you who have believed, do not violate the rites of Allah or the sacred month.<br>Nor the sacrificial animals, nor the garlands, nor those coming to the Sacred House seeking bounty from their Lord and His approval. This surah contains rulings on contracts, the lawful and the forbidden, guiding the believers in their daily lives.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ô vous qui avez cru, remplissez vos engagements. Les bêtes de bétail vous sont permises, sauf ce qui vous est récité, sans que la chasse soit permise lorsque vous êtes en état d'ihram. En vérité, Allah décide ce qu’Il veut. Ô vous qui avez cru, ne profanez pas les rites d’Allah ni le mois sacré.<br>Ni les offrandes, ni les guirlandes, ni ceux qui se rendent à la Maison Sacrée en quête de la grâce de leur Seigneur et de Sa satisfaction. Cette sourate contient des règles sur les contrats, le licite et l’illicite, guidant les croyants dans leur vie quotidienne."
    },
    41: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>ٱلْحَمْدُ لِلَّهِ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ وَجَعَلَ ٱلظُّلُمَٰتِ وَٱلنُّورَ ۖ ثُمَّ ٱلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ يَعْدِلُونَ ۝ هُوَ ٱلَّذِى خَلَقَكُم مِّن طِينٍ ثُمَّ قَضَىٰٓ أَجَلًا ۖ وَأَجَلٌ مُّسَمًّى عِندَهُۥ ۖ ثُمَّ أَنتُمْ تَمْتَرُونَ ۝ وَهُوَ ٱللَّهُ فِى ٱلسَّمَٰوَٰتِ وَفِى ٱلْأَرْضِ<br>يَعْلَمُ سِرَّكُمْ وَجَهْرَكُمْ وَيَعْلَمُ مَا تَكْسِبُونَ ۝ هَذِهِ السُّورَةُ تُؤَكِّدُ عَلَىٰ تَوْحِيدِ ٱللَّهِ وَتَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ إِبْرَاهِيمَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Praise be to Allah, who created the heavens and the earth and made the darkness and the light. Then those who disbelieve equate others with their Lord. It is He who created you from clay and then decreed a term and a specified time known to Him; yet you are in doubt. And He is Allah in the heavens and on the earth.<br>He knows your secret and what you make public, and He knows that which you earn. This surah emphasizes the oneness of Allah and narrates stories of prophets like Abraham, teaching lessons of faith and obedience.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Louange à Allah, qui a créé les cieux et la terre et a fait les ténèbres et la lumière. Puis ceux qui mécroient attribuent des égaux à leur Seigneur. C’est Lui qui vous a créés d’argile, puis a fixé un terme, et un terme déterminé est auprès de Lui ; et pourtant vous doutez. Il est Allah dans les cieux et sur la terre.<br>Il connaît votre secret et ce que vous divulguez, et Il sait ce que vous acquérez. Cette sourate met l’accent sur l’unicité d’Allah et raconte les histoires de prophètes comme Abraham, enseignant des leçons de foi et d’obéissance."
    },
    42: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>المص ۝ كِتَٰبٌ أُنزِلَ إِلَيْكَ فَلَا يَكُن فِى صَدْرِكَ حَرَجٌ مِّنْهُ لِتُنذِرَ بِهِۦ وَذِكْرَىٰ لِلْمُؤْمِنِينَ ۝ ٱتَّبِعُوا۟ مَآ أُنزِلَ إِلَيْكُم مِّن رَّبِّكُمْ وَلَا تَتَّبِعُوا۟ مِن دُونِهِۦٓ أَوْلِيَآءَ ۗ قَلِيلًا مَّا تَذَكَّرُونَ ۝ وَكَم مِّن قَرْيَةٍ أَهْلَكْنَٰهَا فَجَآءَهَا بَأْسُنَا بَيَٰتًا أَوْ هُمْ قَآئِلُونَ<br>فَمَا كَانَ دَعْوَىٰهُمْ إِذْ جَآءَهُم بَأْسُنَآ إِلَّآ أَن قَالُوٓا۟ إِنَّا كُنَّا ظَٰلِمِينَ ۝ هَذِهِ السُّورَةُ تَحْكِي قِصَصَ الْأَنْبِيَاءِ مِثْلَ نُوحٍ وَمُوسَىٰ وَتُحَذِّرُ مِنَ الْعَذَابِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>Alif Lam Mim Sad. A Book revealed to you—so let there be no discomfort in your heart from it—that you may warn thereby and as a reminder to the believers. Follow what has been revealed to you from your Lord and do not follow other than Him as allies. Little do you remember. And how many a city We destroyed, and Our punishment came to them at night or while they were sleeping at noon.<br>Then their plea when Our punishment came to them was only that they said, 'Indeed, we were wrongdoers.' This surah narrates the stories of prophets like Noah and Moses, warning against the punishment for disbelief.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Alif Lam Mim Sad. Un Livre qui t’a été révélé—qu’il n’y ait donc pas de gêne dans ton cœur à cause de lui—afin que tu avertisses par lui et qu’il soit un rappel pour les croyants. Suivez ce qui vous a été révélé de votre Seigneur et ne suivez pas d’autres alliés en dehors de Lui. Peu vous vous souvenez. Combien de cités avons-Nous détruites, et Notre châtiment leur est venu la nuit ou pendant qu’ils faisaient la sieste à midi.<br>Leur seule plainte, lorsque Notre châtiment les atteignit, fut de dire : 'En vérité, nous étions injustes.' Cette sourate raconte les histoires de prophètes comme Noé et Moïse, mettant en garde contre le châtiment pour l’incroyance."
    },
    43: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>يَسْـَٔلُونَكَ عَنِ ٱلْأَنفَالِ ۖ قُلِ ٱلْأَنفَالُ لِلَّهِ وَٱلرَّسُولِ ۖ فَٱتَّقُوا۟ ٱللَّهَ وَأَصْلِحُوا۟ ذَاتَ بَيْنِكُمْ ۖ وَأَطِيعُوا۟ ٱللَّهَ وَرَسُولَهُۥٓ إِن كُنتُم مُّؤْمِنِينَ ۝ إِنَّمَا ٱلْمُؤْمِنُونَ ٱلَّذِينَ إِذَا ذُكِرَ ٱللَّهُ وَجِلَتْ قُلُوبُهُمْ وَإِذَا تُلِيَتْ عَلَيْهِمْ ءَايَٰتُهُۥ زَادَتْهُمْ إِيمَٰنًا<br>وَعَلَىٰ رَبِّهِمْ يَتَوَكَّلُونَ ۝ هَذِهِ السُّورَةُ تَتَحَدَّثُ عَنْ غَنَائِمِ الْحَرْبِ وَمَعْرَكَةِ بَدْرٍ وَتُعَلِّمُ الْمُؤْمِنِينَ الصَّبْرَ وَالطَّاعَةَ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>They ask you about the spoils of war. Say, 'The spoils belong to Allah and the Messenger, so fear Allah and set right the matters between you, and obey Allah and His Messenger if you are believers.' The true believers are those whose hearts tremble when Allah is mentioned, and when His verses are recited to them, it increases their faith.<br>And they rely upon their Lord. This surah discusses the spoils of war and the Battle of Badr, teaching the believers patience and obedience to Allah and His Messenger.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Ils te questionnent au sujet des butins. Dis : 'Les butins appartiennent à Allah et au Messager, alors craignez Allah et réglez vos différends, et obéissez à Allah et à Son Messager si vous êtes croyants.' Les vrais croyants sont ceux dont les cœurs frémissent quand Allah est mentionné, et lorsque Ses versets leur sont récités, cela augmente leur foi.<br>Et ils s’en remettent à leur Seigneur. Cette sourate parle des butins de guerre et de la bataille de Badr, enseignant aux croyants la patience et l’obéissance à Allah et à Son Messager."
    },
    44: {
        ar: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ<br>بَرَاءَةٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلَّذِينَ عَٰهَدتُّم مِّنَ ٱلْمُشْرِكِينَ ۝ فَسِيحُوا۟ فِى ٱلْأَرْضِ أَرْبَعَةَ أَشْهُرٍ وَٱعْلَمُوٓا۟ أَنَّكُمْ غَيْرُ مُعْجِزِى ٱللَّهِ ۖ وَأَنَّ ٱللَّهَ مُخْزِى ٱلْكَٰفِرِينَ ۝ وَأَذَٰنٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلنَّاسِ يَوْمَ ٱلْحَجِّ ٱلْأَكْبَرِ<br>أَنَّ ٱللَّهَ بَرِىٓءٌ مِّنَ ٱلْمُشْرِكِينَ ۙ وَرَسُولُهُۥ ۚ هَذِهِ السُّورَةُ تُعْلِنُ انْتِهَاءَ الْعَهْدِ مَعَ الْمُشْرِكِينَ وَتُحَدِّدُ أَحْكَامَ الْجِهَادِ.",
        en: "In the name of Allah, the Most Gracious, the Most Merciful<br>A declaration of disassociation from Allah and His Messenger to those with whom you had made a treaty among the polytheists. So travel freely in the land for four months but know that you cannot escape Allah and that Allah will disgrace the disbelievers. And an announcement from Allah and His Messenger to the people on the day of the greater pilgrimage.<br>That Allah is free from the polytheists, and so is His Messenger. This surah declares the end of treaties with the polytheists and outlines the rules of jihad, emphasizing the importance of upholding faith.",
        fr: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux<br>Une déclaration de rupture de la part d’Allah et de Son Messager envers ceux des polythéistes avec lesquels vous aviez conclu un pacte. Parcourez librement la terre pendant quatre mois, mais sachez que vous ne saurez échapper à Allah et qu’Allah couvrira d’opprobre les mécréants. Et un appel d’Allah et de Son Messager aux gens le jour du grand pèlerinage.<br>Qu’Allah est dégagé des polythéistes, ainsi que Son Messager. Cette sourate annonce la fin des pactes avec les polythéistes et établit les règles du jihad, soulignant l’importance de maintenir la foi."
    },
   }
